# -*- coding: utf-8 -*-
"""ridge and lasso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WsoRJ__4f0ouVxg4lmkOAqlK1yEPJK5_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso

# Load the diabetes dataset
data = load_diabetes()

X = data.data
y = data.target

X = data.data
y = data.target

x

y

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize Ridge and Lasso regression models
ridge_reg = Ridge(alpha=1.0)
lasso_reg = Lasso(alpha=0.1)

# Fit the models
ridge_reg.fit(X_train, y_train)
lasso_reg.fit(X_train, y_train)

# Get the coefficients
ridge_coefs = ridge_reg.coef_
lasso_coefs = lasso_reg.coef_

# Plotting the coefficients
features = data.feature_names
x = np.arange(len(features))

plt.figure(figsize=(10, 6))

plt.bar(x - 0.2, ridge_coefs, width=0.4, label='Ridge Coefficients')
plt.bar(x + 0.2, lasso_coefs, width=0.4, label='Lasso Coefficients')

plt.xticks(x, features, rotation=45)
plt.ylabel('Coefficient Value')
plt.title('Ridge vs Lasso Coefficients')
plt.legend()
plt.show()